var WMS_V_1_3_0 = {
  name: 'WMS_V_1_3_0',
  defaultElementNamespaceURI: 'http:\/\/www.opengis.net\/wms',
  typeInfos: [{
      type: 'classInfo',
      localName: 'Service',
      propertyInfos: [{
          type: 'element',
          name: 'name',
          elementName: 'Name',
          typeInfo: 'String'
        }, {
          type: 'element',
          name: 'title',
          elementName: 'Title',
          typeInfo: 'String'
        }, {
          type: 'element',
          name: '_abstract',
          elementName: 'Abstract',
          typeInfo: 'String'
        }, {
          type: 'element',
          name: 'keywordList',
          elementName: 'KeywordList',
          typeInfo: 'WMS_V_1_3_0.KeywordList'
        }, {
          type: 'element',
          name: 'onlineResource',
          elementName: 'OnlineResource',
          typeInfo: 'WMS_V_1_3_0.OnlineResource'
        }, {
          type: 'element',
          name: 'contactInformation',
          elementName: 'ContactInformation',
          typeInfo: 'WMS_V_1_3_0.ContactInformation'
        }, {
          type: 'element',
          name: 'fees',
          elementName: 'Fees',
          typeInfo: 'String'
        }, {
          type: 'element',
          name: 'accessConstraints',
          elementName: 'AccessConstraints',
          typeInfo: 'String'
        }, {
          type: 'element',
          name: 'layerLimit',
          elementName: 'LayerLimit',
          typeInfo: 'Integer'
        }, {
          type: 'element',
          name: 'maxWidth',
          elementName: 'MaxWidth',
          typeInfo: 'Integer'
        }, {
          type: 'element',
          name: 'maxHeight',
          elementName: 'MaxHeight',
          typeInfo: 'Integer'
        }]
    }, {
      type: 'classInfo',
      localName: 'KeywordList',
      propertyInfos: [{
          type: 'element',
          name: 'keyword',
          collection: true,
          elementName: 'Keyword',
          typeInfo: 'WMS_V_1_3_0.Keyword'
        }]
    }, {
      type: 'classInfo',
      localName: 'Keyword',
      propertyInfos: [{
          name: 'value',
          typeInfo: 'String',
          type: 'value'
        }, {
          name: 'vocabulary',
          typeInfo: 'String',
          attributeName: 'vocabulary',
          type: 'attribute'
        }]
    }, {
      type: 'classInfo',
      localName: 'OnlineResource',
      propertyInfos: [{
          name: 'type',
          typeInfo: 'String',
          attributeName: {
            localPart: 'type',
            namespaceURI: 'http:\/\/www.w3.org\/1999\/xlink'
          },
          type: 'attribute'
        }, {
          name: 'href',
          typeInfo: 'String',
          attributeName: {
            localPart: 'href',
            namespaceURI: 'http:\/\/www.w3.org\/1999\/xlink'
          },
          type: 'attribute'
        }, {
          name: 'role',
          typeInfo: 'String',
          attributeName: {
            localPart: 'role',
            namespaceURI: 'http:\/\/www.w3.org\/1999\/xlink'
          },
          type: 'attribute'
        }, {
          name: 'arcrole',
          typeInfo: 'String',
          attributeName: {
            localPart: 'arcrole',
            namespaceURI: 'http:\/\/www.w3.org\/1999\/xlink'
          },
          type: 'attribute'
        }, {
          name: 'title',
          typeInfo: 'String',
          attributeName: {
            localPart: 'title',
            namespaceURI: 'http:\/\/www.w3.org\/1999\/xlink'
          },
          type: 'attribute'
        }, {
          name: 'show',
          typeInfo: 'String',
          attributeName: {
            localPart: 'show',
            namespaceURI: 'http:\/\/www.w3.org\/1999\/xlink'
          },
          type: 'attribute'
        }, {
          name: 'actuate',
          typeInfo: 'String',
          attributeName: {
            localPart: 'actuate',
            namespaceURI: 'http:\/\/www.w3.org\/1999\/xlink'
          },
          type: 'attribute'
        }]
    }, {
      type: 'classInfo',
      localName: 'ContactInformation',
      propertyInfos: [{
          type: 'element',
          name: 'contactPersonPrimary',
          elementName: 'ContactPersonPrimary',
          typeInfo: 'WMS_V_1_3_0.ContactPersonPrimary'
        }, {
          type: 'element',
          name: 'contactPosition',
          elementName: 'ContactPosition',
          typeInfo: 'String'
        }, {
          type: 'element',
          name: 'contactAddress',
          elementName: 'ContactAddress',
          typeInfo: 'WMS_V_1_3_0.ContactAddress'
        }, {
          type: 'element',
          name: 'contactVoiceTelephone',
          elementName: 'ContactVoiceTelephone',
          typeInfo: 'String'
        }, {
          type: 'element',
          name: 'contactFacsimileTelephone',
          elementName: 'ContactFacsimileTelephone',
          typeInfo: 'String'
        }, {
          type: 'element',
          name: 'contactElectronicMailAddress',
          elementName: 'ContactElectronicMailAddress',
          typeInfo: 'String'
        }]
    }, {
      type: 'classInfo',
      localName: 'ContactPersonPrimary',
      propertyInfos: [{
          type: 'element',
          name: 'contactPerson',
          elementName: 'ContactPerson',
          typeInfo: 'String'
        }, {
          type: 'element',
          name: 'contactOrganization',
          elementName: 'ContactOrganization',
          typeInfo: 'String'
        }]
    }, {
      type: 'classInfo',
      localName: 'ContactAddress',
      propertyInfos: [{
          type: 'element',
          name: 'addressType',
          elementName: 'AddressType',
          typeInfo: 'String'
        }, {
          type: 'element',
          name: 'address',
          elementName: 'Address',
          typeInfo: 'String'
        }, {
          type: 'element',
          name: 'city',
          elementName: 'City',
          typeInfo: 'String'
        }, {
          type: 'element',
          name: 'stateOrProvince',
          elementName: 'StateOrProvince',
          typeInfo: 'String'
        }, {
          type: 'element',
          name: 'postCode',
          elementName: 'PostCode',
          typeInfo: 'String'
        }, {
          type: 'element',
          name: 'country',
          elementName: 'Country',
          typeInfo: 'String'
        }]
    }, {
      type: 'classInfo',
      localName: 'Attribution',
      propertyInfos: [{
          type: 'element',
          name: 'title',
          elementName: 'Title',
          typeInfo: 'String'
        }, {
          type: 'element',
          name: 'onlineResource',
          elementName: 'OnlineResource',
          typeInfo: 'WMS_V_1_3_0.OnlineResource'
        }, {
          type: 'element',
          name: 'logoURL',
          elementName: 'LogoURL',
          typeInfo: 'WMS_V_1_3_0.LogoURL'
        }]
    }, {
      type: 'classInfo',
      localName: 'LogoURL',
      propertyInfos: [{
          type: 'element',
          name: 'format',
          elementName: 'Format',
          typeInfo: 'String'
        }, {
          type: 'element',
          name: 'onlineResource',
          elementName: 'OnlineResource',
          typeInfo: 'WMS_V_1_3_0.OnlineResource'
        }, {
          name: 'width',
          typeInfo: 'Integer',
          attributeName: 'width',
          type: 'attribute'
        }, {
          name: 'height',
          typeInfo: 'Integer',
          attributeName: 'height',
          type: 'attribute'
        }]
    }, {
      type: 'classInfo',
      localName: 'HTTP',
      propertyInfos: [{
          type: 'element',
          name: 'get',
          elementName: 'Get',
          typeInfo: 'WMS_V_1_3_0.Get'
        }, {
          type: 'element',
          name: 'post',
          elementName: 'Post',
          typeInfo: 'WMS_V_1_3_0.Post'
        }]
    }, {
      type: 'classInfo',
      localName: 'Get',
      propertyInfos: [{
          type: 'element',
          name: 'onlineResource',
          elementName: 'OnlineResource',
          typeInfo: 'WMS_V_1_3_0.OnlineResource'
        }]
    }, {
      type: 'classInfo',
      localName: 'Post',
      propertyInfos: [{
          type: 'element',
          name: 'onlineResource',
          elementName: 'OnlineResource',
          typeInfo: 'WMS_V_1_3_0.OnlineResource'
        }]
    }, {
      type: 'classInfo',
      localName: 'AuthorityURL',
      propertyInfos: [{
          type: 'element',
          name: 'onlineResource',
          elementName: 'OnlineResource',
          typeInfo: 'WMS_V_1_3_0.OnlineResource'
        }, {
          name: 'name',
          typeInfo: 'String',
          attributeName: 'name',
          type: 'attribute'
        }]
    }, {
      type: 'classInfo',
      localName: 'Style',
      propertyInfos: [{
          type: 'element',
          name: 'name',
          elementName: 'Name',
          typeInfo: 'String'
        }, {
          type: 'element',
          name: 'title',
          elementName: 'Title',
          typeInfo: 'String'
        }, {
          type: 'element',
          name: '_abstract',
          elementName: 'Abstract',
          typeInfo: 'String'
        }, {
          type: 'element',
          name: 'legendURL',
          collection: true,
          elementName: 'LegendURL',
          typeInfo: 'WMS_V_1_3_0.LegendURL'
        }, {
          type: 'element',
          name: 'styleSheetURL',
          elementName: 'StyleSheetURL',
          typeInfo: 'WMS_V_1_3_0.StyleSheetURL'
        }, {
          type: 'element',
          name: 'styleURL',
          elementName: 'StyleURL',
          typeInfo: 'WMS_V_1_3_0.StyleURL'
        }]
    }, {
      type: 'classInfo',
      localName: 'LegendURL',
      propertyInfos: [{
          type: 'element',
          name: 'format',
          elementName: 'Format',
          typeInfo: 'String'
        }, {
          type: 'element',
          name: 'onlineResource',
          elementName: 'OnlineResource',
          typeInfo: 'WMS_V_1_3_0.OnlineResource'
        }, {
          name: 'width',
          typeInfo: 'Integer',
          attributeName: 'width',
          type: 'attribute'
        }, {
          name: 'height',
          typeInfo: 'Integer',
          attributeName: 'height',
          type: 'attribute'
        }]
    }, {
      type: 'classInfo',
      localName: 'StyleSheetURL',
      propertyInfos: [{
          type: 'element',
          name: 'format',
          elementName: 'Format',
          typeInfo: 'String'
        }, {
          type: 'element',
          name: 'onlineResource',
          elementName: 'OnlineResource',
          typeInfo: 'WMS_V_1_3_0.OnlineResource'
        }]
    }, {
      type: 'classInfo',
      localName: 'StyleURL',
      propertyInfos: [{
          type: 'element',
          name: 'format',
          elementName: 'Format',
          typeInfo: 'String'
        }, {
          type: 'element',
          name: 'onlineResource',
          elementName: 'OnlineResource',
          typeInfo: 'WMS_V_1_3_0.OnlineResource'
        }]
    }, {
      type: 'classInfo',
      localName: 'WMSCapabilities',
      propertyInfos: [{
          type: 'element',
          name: 'service',
          elementName: 'Service',
          typeInfo: 'WMS_V_1_3_0.Service'
        }, {
          type: 'element',
          name: 'capability',
          elementName: 'Capability',
          typeInfo: 'WMS_V_1_3_0.Capability'
        }, {
          name: 'version',
          typeInfo: 'String',
          attributeName: 'version',
          type: 'attribute'
        }, {
          name: 'updateSequence',
          typeInfo: 'String',
          attributeName: 'updateSequence',
          type: 'attribute'
        }]
    }, {
      type: 'classInfo',
      localName: 'Capability',
      propertyInfos: [{
          type: 'element',
          name: 'request',
          elementName: 'Request',
          typeInfo: 'WMS_V_1_3_0.Request'
        }, {
          type: 'element',
          name: 'exception',
          elementName: 'Exception',
          typeInfo: 'WMS_V_1_3_0.Exception'
        }, {
          name: 'extendedCapabilities',
          collection: true,
          domAllowed: true,
          type: 'anyElement'
        }, {
          type: 'element',
          name: 'layer',
          elementName: 'Layer',
          typeInfo: 'WMS_V_1_3_0.Layer'
        }]
    }, {
      type: 'classInfo',
      localName: 'Request',
      propertyInfos: [{
          type: 'element',
          name: 'getCapabilities',
          elementName: 'GetCapabilities',
          typeInfo: 'WMS_V_1_3_0.OperationType'
        }, {
          type: 'element',
          name: 'getMap',
          elementName: 'GetMap',
          typeInfo: 'WMS_V_1_3_0.OperationType'
        }, {
          type: 'element',
          name: 'getFeatureInfo',
          elementName: 'GetFeatureInfo',
          typeInfo: 'WMS_V_1_3_0.OperationType'
        }, {
          type: 'element',
          name: 'extendedOperation',
          collection: true,
          elementName: '_ExtendedOperation',
          typeInfo: 'WMS_V_1_3_0.OperationType'
        }]
    }, {
      type: 'classInfo',
      localName: 'OperationType',
      propertyInfos: [{
          type: 'element',
          name: 'format',
          collection: true,
          elementName: 'Format',
          typeInfo: 'String'
        }, {
          type: 'element',
          name: 'dcpType',
          collection: true,
          elementName: 'DCPType',
          typeInfo: 'WMS_V_1_3_0.DCPType'
        }]
    }, {
      type: 'classInfo',
      localName: 'Exception',
      propertyInfos: [{
          type: 'element',
          name: 'format',
          collection: true,
          elementName: 'Format',
          typeInfo: 'String'
        }]
    }, {
      type: 'classInfo',
      localName: 'Layer',
      propertyInfos: [{
          type: 'element',
          name: 'name',
          elementName: 'Name',
          typeInfo: 'String'
        }, {
          type: 'element',
          name: 'title',
          elementName: 'Title',
          typeInfo: 'String'
        }, {
          type: 'element',
          name: '_abstract',
          elementName: 'Abstract',
          typeInfo: 'String'
        }, {
          type: 'element',
          name: 'keywordList',
          elementName: 'KeywordList',
          typeInfo: 'WMS_V_1_3_0.KeywordList'
        }, {
          type: 'element',
          name: 'crs',
          collection: true,
          elementName: 'CRS',
          typeInfo: 'String'
        }, {
          type: 'element',
          name: 'exGeographicBoundingBox',
          elementName: 'EX_GeographicBoundingBox',
          typeInfo: 'WMS_V_1_3_0.EXGeographicBoundingBox'
        }, {
          type: 'element',
          name: 'boundingBox',
          collection: true,
          elementName: 'BoundingBox',
          typeInfo: 'WMS_V_1_3_0.BoundingBox'
        }, {
          type: 'element',
          name: 'dimension',
          collection: true,
          elementName: 'Dimension',
          typeInfo: 'WMS_V_1_3_0.Dimension'
        }, {
          type: 'element',
          name: 'attribution',
          elementName: 'Attribution',
          typeInfo: 'WMS_V_1_3_0.Attribution'
        }, {
          type: 'element',
          name: 'authorityURL',
          collection: true,
          elementName: 'AuthorityURL',
          typeInfo: 'WMS_V_1_3_0.AuthorityURL'
        }, {
          type: 'element',
          name: 'identifier',
          collection: true,
          elementName: 'Identifier',
          typeInfo: 'WMS_V_1_3_0.Identifier'
        }, {
          type: 'element',
          name: 'metadataURL',
          collection: true,
          elementName: 'MetadataURL',
          typeInfo: 'WMS_V_1_3_0.MetadataURL'
        }, {
          type: 'element',
          name: 'dataURL',
          collection: true,
          elementName: 'DataURL',
          typeInfo: 'WMS_V_1_3_0.DataURL'
        }, {
          type: 'element',
          name: 'featureListURL',
          collection: true,
          elementName: 'FeatureListURL',
          typeInfo: 'WMS_V_1_3_0.FeatureListURL'
        }, {
          type: 'element',
          name: 'style',
          collection: true,
          elementName: 'Style',
          typeInfo: 'WMS_V_1_3_0.Style'
        }, {
          type: 'element',
          name: 'minScaleDenominator',
          elementName: 'MinScaleDenominator',
          typeInfo: 'Double'
        }, {
          type: 'element',
          name: 'maxScaleDenominator',
          elementName: 'MaxScaleDenominator',
          typeInfo: 'Double'
        }, {
          type: 'element',
          name: 'layer',
          collection: true,
          elementName: 'Layer',
          typeInfo: 'WMS_V_1_3_0.Layer'
        }, {
          name: 'queryable',
          typeInfo: 'Boolean',
          attributeName: 'queryable',
          type: 'attribute'
        }, {
          name: 'cascaded',
          typeInfo: 'Integer',
          attributeName: 'cascaded',
          type: 'attribute'
        }, {
          name: 'opaque',
          typeInfo: 'Boolean',
          attributeName: 'opaque',
          type: 'attribute'
        }, {
          name: 'noSubsets',
          typeInfo: 'Boolean',
          attributeName: 'noSubsets',
          type: 'attribute'
        }, {
          name: 'fixedWidth',
          typeInfo: 'Integer',
          attributeName: 'fixedWidth',
          type: 'attribute'
        }, {
          name: 'fixedHeight',
          typeInfo: 'Integer',
          attributeName: 'fixedHeight',
          type: 'attribute'
        }]
    }, {
      type: 'classInfo',
      localName: 'EXGeographicBoundingBox',
      propertyInfos: [{
          type: 'element',
          name: 'westBoundLongitude',
          elementName: 'westBoundLongitude',
          typeInfo: 'Double'
        }, {
          type: 'element',
          name: 'eastBoundLongitude',
          elementName: 'eastBoundLongitude',
          typeInfo: 'Double'
        }, {
          type: 'element',
          name: 'southBoundLatitude',
          elementName: 'southBoundLatitude',
          typeInfo: 'Double'
        }, {
          type: 'element',
          name: 'northBoundLatitude',
          elementName: 'northBoundLatitude',
          typeInfo: 'Double'
        }]
    }, {
      type: 'classInfo',
      localName: 'BoundingBox',
      propertyInfos: [{
          name: 'crs',
          typeInfo: 'String',
          attributeName: 'CRS',
          type: 'attribute'
        }, {
          name: 'minx',
          typeInfo: 'Double',
          attributeName: 'minx',
          type: 'attribute'
        }, {
          name: 'miny',
          typeInfo: 'Double',
          attributeName: 'miny',
          type: 'attribute'
        }, {
          name: 'maxx',
          typeInfo: 'Double',
          attributeName: 'maxx',
          type: 'attribute'
        }, {
          name: 'maxy',
          typeInfo: 'Double',
          attributeName: 'maxy',
          type: 'attribute'
        }, {
          name: 'resx',
          typeInfo: 'Double',
          attributeName: 'resx',
          type: 'attribute'
        }, {
          name: 'resy',
          typeInfo: 'Double',
          attributeName: 'resy',
          type: 'attribute'
        }]
    }, {
      type: 'classInfo',
      localName: 'Dimension',
      propertyInfos: [{
          name: 'value',
          typeInfo: 'String',
          type: 'value'
        }, {
          name: 'name',
          typeInfo: 'String',
          attributeName: 'name',
          type: 'attribute'
        }, {
          name: 'units',
          typeInfo: 'String',
          attributeName: 'units',
          type: 'attribute'
        }, {
          name: 'unitSymbol',
          typeInfo: 'String',
          attributeName: 'unitSymbol',
          type: 'attribute'
        }, {
          name: '_default',
          typeInfo: 'String',
          attributeName: 'default',
          type: 'attribute'
        }, {
          name: 'multipleValues',
          typeInfo: 'Boolean',
          attributeName: 'multipleValues',
          type: 'attribute'
        }, {
          name: 'nearestValue',
          typeInfo: 'Boolean',
          attributeName: 'nearestValue',
          type: 'attribute'
        }, {
          name: 'current',
          typeInfo: 'Boolean',
          attributeName: 'current',
          type: 'attribute'
        }]
    }, {
      type: 'classInfo',
      localName: 'Identifier',
      propertyInfos: [{
          name: 'value',
          typeInfo: 'String',
          type: 'value'
        }, {
          name: 'authority',
          typeInfo: 'String',
          attributeName: 'authority',
          type: 'attribute'
        }]
    }, {
      type: 'classInfo',
      localName: 'MetadataURL',
      propertyInfos: [{
          type: 'element',
          name: 'format',
          elementName: 'Format',
          typeInfo: 'String'
        }, {
          type: 'element',
          name: 'onlineResource',
          elementName: 'OnlineResource',
          typeInfo: 'WMS_V_1_3_0.OnlineResource'
        }, {
          name: 'type',
          typeInfo: 'String',
          attributeName: 'type',
          type: 'attribute'
        }]
    }, {
      type: 'classInfo',
      localName: 'DataURL',
      propertyInfos: [{
          type: 'element',
          name: 'format',
          elementName: 'Format',
          typeInfo: 'String'
        }, {
          type: 'element',
          name: 'onlineResource',
          elementName: 'OnlineResource',
          typeInfo: 'WMS_V_1_3_0.OnlineResource'
        }]
    }, {
      type: 'classInfo',
      localName: 'FeatureListURL',
      propertyInfos: [{
          type: 'element',
          name: 'format',
          elementName: 'Format',
          typeInfo: 'String'
        }, {
          type: 'element',
          name: 'onlineResource',
          elementName: 'OnlineResource',
          typeInfo: 'WMS_V_1_3_0.OnlineResource'
        }]
    }, {
      type: 'classInfo',
      localName: 'DCPType',
      propertyInfos: [{
          type: 'element',
          name: 'http',
          elementName: 'HTTP',
          typeInfo: 'WMS_V_1_3_0.HTTP'
        }]
    }, {
      type: 'classInfo',
      localName: 'ServiceExceptionReport',
      propertyInfos: [{
          type: 'element',
          name: 'serviceException',
          collection: true,
          elementName: {
            localPart: 'ServiceException',
            namespaceURI: 'http:\/\/www.opengis.net\/ogc'
          },
          typeInfo: 'WMS_V_1_3_0.ServiceExceptionType'
        }, {
          name: 'version',
          typeInfo: 'String',
          attributeName: 'version',
          type: 'attribute'
        }]
    }, {
      type: 'classInfo',
      localName: 'ServiceExceptionType',
      propertyInfos: [{
          name: 'value',
          typeInfo: 'String',
          type: 'value'
        }, {
          name: 'code',
          typeInfo: 'String',
          attributeName: 'code',
          type: 'attribute'
        }, {
          name: 'locator',
          typeInfo: 'String',
          attributeName: 'locator',
          type: 'attribute'
        }]
    }],
  elementInfos: [{
      elementName: 'Service',
      typeInfo: 'WMS_V_1_3_0.Service'
    }, {
      elementName: 'KeywordList',
      typeInfo: 'WMS_V_1_3_0.KeywordList'
    }, {
      elementName: 'Keyword',
      typeInfo: 'WMS_V_1_3_0.Keyword'
    }, {
      elementName: 'OnlineResource',
      typeInfo: 'WMS_V_1_3_0.OnlineResource'
    }, {
      elementName: 'ContactInformation',
      typeInfo: 'WMS_V_1_3_0.ContactInformation'
    }, {
      elementName: 'ContactPersonPrimary',
      typeInfo: 'WMS_V_1_3_0.ContactPersonPrimary'
    }, {
      elementName: 'ContactAddress',
      typeInfo: 'WMS_V_1_3_0.ContactAddress'
    }, {
      elementName: 'Attribution',
      typeInfo: 'WMS_V_1_3_0.Attribution'
    }, {
      elementName: 'LogoURL',
      typeInfo: 'WMS_V_1_3_0.LogoURL'
    }, {
      elementName: 'HTTP',
      typeInfo: 'WMS_V_1_3_0.HTTP'
    }, {
      elementName: 'Get',
      typeInfo: 'WMS_V_1_3_0.Get'
    }, {
      elementName: 'Post',
      typeInfo: 'WMS_V_1_3_0.Post'
    }, {
      elementName: 'AuthorityURL',
      typeInfo: 'WMS_V_1_3_0.AuthorityURL'
    }, {
      elementName: 'Style',
      typeInfo: 'WMS_V_1_3_0.Style'
    }, {
      elementName: 'LegendURL',
      typeInfo: 'WMS_V_1_3_0.LegendURL'
    }, {
      elementName: 'StyleSheetURL',
      typeInfo: 'WMS_V_1_3_0.StyleSheetURL'
    }, {
      elementName: 'StyleURL',
      typeInfo: 'WMS_V_1_3_0.StyleURL'
    }, {
      elementName: 'WMS_Capabilities',
      typeInfo: 'WMS_V_1_3_0.WMSCapabilities'
    }, {
      elementName: 'Capability',
      typeInfo: 'WMS_V_1_3_0.Capability'
    }, {
      elementName: 'Request',
      typeInfo: 'WMS_V_1_3_0.Request'
    }, {
      elementName: 'Exception',
      typeInfo: 'WMS_V_1_3_0.Exception'
    }, {
      elementName: 'Layer',
      typeInfo: 'WMS_V_1_3_0.Layer'
    }, {
      elementName: 'EX_GeographicBoundingBox',
      typeInfo: 'WMS_V_1_3_0.EXGeographicBoundingBox'
    }, {
      elementName: 'BoundingBox',
      typeInfo: 'WMS_V_1_3_0.BoundingBox'
    }, {
      elementName: 'Dimension',
      typeInfo: 'WMS_V_1_3_0.Dimension'
    }, {
      elementName: 'Identifier',
      typeInfo: 'WMS_V_1_3_0.Identifier'
    }, {
      elementName: 'MetadataURL',
      typeInfo: 'WMS_V_1_3_0.MetadataURL'
    }, {
      elementName: 'DataURL',
      typeInfo: 'WMS_V_1_3_0.DataURL'
    }, {
      elementName: 'FeatureListURL',
      typeInfo: 'WMS_V_1_3_0.FeatureListURL'
    }, {
      elementName: 'DCPType',
      typeInfo: 'WMS_V_1_3_0.DCPType'
    }, {
      elementName: {
        localPart: 'ServiceExceptionReport',
        namespaceURI: 'http:\/\/www.opengis.net\/ogc'
      },
      typeInfo: 'WMS_V_1_3_0.ServiceExceptionReport'
    }, {
      elementName: 'Name',
      typeInfo: 'String'
    }, {
      elementName: 'MinScaleDenominator',
      typeInfo: 'Double'
    }, {
      elementName: 'PostCode',
      typeInfo: 'String'
    }, {
      elementName: 'MaxHeight',
      typeInfo: 'Integer'
    }, {
      elementName: 'Address',
      typeInfo: 'String'
    }, {
      elementName: 'ContactFacsimileTelephone',
      typeInfo: 'String'
    }, {
      elementName: 'AddressType',
      typeInfo: 'String'
    }, {
      elementName: 'ContactVoiceTelephone',
      typeInfo: 'String'
    }, {
      elementName: 'Abstract',
      typeInfo: 'String'
    }, {
      elementName: 'MaxWidth',
      typeInfo: 'Integer'
    }, {
      elementName: 'AccessConstraints',
      typeInfo: 'String'
    }, {
      elementName: '_ExtendedCapabilities',
      typeInfo: 'AnyType'
    }, {
      elementName: 'ContactPerson',
      typeInfo: 'String'
    }, {
      elementName: 'GetCapabilities',
      typeInfo: 'WMS_V_1_3_0.OperationType'
    }, {
      elementName: 'LayerLimit',
      typeInfo: 'Integer'
    }, {
      elementName: 'ContactOrganization',
      typeInfo: 'String'
    }, {
      elementName: '_ExtendedOperation',
      typeInfo: 'WMS_V_1_3_0.OperationType'
    }, {
      elementName: 'Country',
      typeInfo: 'String'
    }, {
      elementName: 'City',
      typeInfo: 'String'
    }, {
      elementName: 'Title',
      typeInfo: 'String'
    }, {
      elementName: 'Fees',
      typeInfo: 'String'
    }, {
      elementName: 'GetMap',
      typeInfo: 'WMS_V_1_3_0.OperationType'
    }, {
      elementName: 'GetFeatureInfo',
      typeInfo: 'WMS_V_1_3_0.OperationType'
    }, {
      elementName: 'StateOrProvince',
      typeInfo: 'String'
    }, {
      elementName: 'Format',
      typeInfo: 'String'
    }, {
      elementName: 'CRS',
      typeInfo: 'String'
    }, {
      elementName: 'MaxScaleDenominator',
      typeInfo: 'Double'
    }, {
      elementName: 'ContactElectronicMailAddress',
      typeInfo: 'String'
    }, {
      elementName: 'ContactPosition',
      typeInfo: 'String'
    }]
};
if (typeof require === 'function') {
  module.exports.WMS_V_1_3_0 = WMS_V_1_3_0;
}